version: 1.4.2.{build}


os: Visual Studio 2015


# Do not build on tags (GitHub only)
skip_tags: true


# branches to build
branches:
  only:
  - master
  - tmp
  - multivolume


# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform:
#  - x86
#  - x64


environment:
  matrix:
  - platform: x86
    CMAKE_ARGS: -G"Visual Studio 14" -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\libplzma\libplzma-install-win-%PLATFORM% -DCMAKE_BUILD_TYPE=Release -DLIBPLZMA_OPT_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%

  - platform: x64
    CMAKE_ARGS: -G"Visual Studio 14 Win64" -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\libplzma\libplzma-install-win-%PLATFORM% -DCMAKE_BUILD_TYPE=Release -DLIBPLZMA_OPT_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%


configuration: Release


# clone directory
clone_folder: c:\dev\libplzma


# scripts that run after cloning repository
install:
  - cd c:\dev\libplzma
  - md libplzma-install-win-%PLATFORM%


build:
  parallel: true
  verbosity: detailed


build_script:
  - cd c:\dev\libplzma
  - md build
  - cd build
  - cmake %CMAKE_ARGS% ..
  - cmake --build . --config Release --parallel 4
  - copy C:\dev\libplzma\build\Release\libplzma.dll C:\dev\libplzma\build\cmake_tests\Release\libplzma.dll
  - ctest --verbose
  - cmake --build . --config Release --target Install
  - cd ..
